# Generated by Django 6.1 on 2026-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehistory',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
