# Generated by Django 6.1 on 2026-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicehistory_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], max_length=20),
        ),
    ]
